= Airponics Chamber
:doc-name: architecture.adoc
:revnumber: v0.1.0
:toc: left

ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT]
image:https://img.shields.io/badge/Contribute%20on-GitHub-orange[Contribute on GitHub, link=https://github.com/earthshuttle/airponics-chamber.git]
image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=/airponics-chamber/airponics-chamber.pdf]
endif::[]

<<<

== Stakeholder Needs

The Airponics Chamber is guided by a series of stakeholder needs, listed below.


=== 1: Optimum aeroponics growth temperature
****
In an aeroponics system, the optimum growth chamber temperature should be between 4 and 30 degrees celsius for successful plant growth.footnote:2-ManualOnQualitySeedPotatoProductionUsingAeroponics[V. Otazú, Manual on Quality Seed Potato Production Using Aeroponics, vol. 44, International Potato Center (CIP), Lima, Peru, 2010, https://doi.org/10.4160/9789290605041]
****



== User Stories

The Airponics Chamber's stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.



== Data Structures
This section covers each data structure type in the *Airponics Chamber*.


