= Airponics Chamber
:doc-name: architecture.adoc
:revnumber: v0.1.0
:toc: left

ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT]
image:https://img.shields.io/badge/Contribute%20on-GitHub-orange[Contribute on GitHub, link=https://github.com/earthshuttle/airponics-chamber.git]
image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=/airponics-chamber/airponics-chamber.pdf]
endif::[]

<<<

== Stakeholder Needs

The Airponics Chamber is guided by a series of stakeholder needs, listed below.


=== 1: Monitoring & Control of Environmental Conditions & Nutrients
****
In an aeroponics system, the environmental conditions & nutrients need to be monitored and controlled for successful plant growth.footnote:1-MonitoringAndControlSystemsInAgricultureUsingIntelligentSensorTechniques[Imran Ali Lakhiar, Gao Jianmin, Tabinda Naz Syed, Farman Ali Chandio, Noman Ali Buttar, Waqar Ahmed Qureshi, "Monitoring and Control Systems in Agriculture Using Intelligent Sensor Techniques: A Review of the Aeroponic System", Journal of Sensors, vol. 2018, Article ID 8672769, 18 pages, 2018. https://doi.org/10.1155/2018/8672769]
****


=== 1.1: Environment Temperature
****
In an aeroponics system, the ideal environment temperature for plant growth is 25 to 30 degrees celsiusfootnote:2-DesignAndImplementationOfIoTSystemForAeroponicChamberTemperatureMonitoring[Charisma Aulia Jamhari, Wahyu Kunto Wibowo, Aulia Rahma Annisa, Teuku Muhammad Roffi, "Design and Implementation of IoT System for Aeroponic Chamber Temperature Monitoring", Vocational Education and Electrical Engineering (ICVEE) 2020 Third International Conference on, pp. 1-4, 2020. https://doi.org/10.1109/ICVEE50212.2020.9243213]
****


=== 1.1.1: Environment Temperature for Tubers
****
In an aeroponics system for tubers, the nominal environment temperature range is 4 to 30 degrees celsius, with an ideal temperature range of 16 to 19 degrees celsius for starting tuber formation.footnote:3-ManualOnQualitySeedPotatoProductionUsingAeroponics[V. Otazú, Manual on Quality Seed Potato Production Using Aeroponics, vol. 44, International Potato Center (CIP), Lima, Peru, 2010. https://doi.org/10.4160/9789290603924]
****


=== 1.1.2: Nutrient Solution Temperature for Tubers
****
In an aeroponics system for tubers, the nutrient solution temperature should not exceed 20 degrees celsius.footnote:3-ManualOnQualitySeedPotatoProductionUsingAeroponics[V. Otazú, Manual on Quality Seed Potato Production Using Aeroponics, vol. 44, International Potato Center (CIP), Lima, Peru, 2010. https://doi.org/10.4160/9789290603924]
****


=== 1.2: Humidity
****
In an aeroponics system, the required relative humidity is above 60% at 25 to 30 degrees celsius.footnote:2-DesignAndImplementationOfIoTSystemForAeroponicChamberTemperatureMonitoring[Charisma Aulia Jamhari, Wahyu Kunto Wibowo, Aulia Rahma Annisa, Teuku Muhammad Roffi, "Design and Implementation of IoT System for Aeroponic Chamber Temperature Monitoring", Vocational Education and Electrical Engineering (ICVEE) 2020 Third International Conference on, pp. 1-4, 2020. https://doi.org/10.1109/ICVEE50212.2020.9243213]
****


=== 1.3: Lights
****
Aeroponically grown plants require varying light spectra, light/dark period, and light intensity.footnote:5-IndoorPlantLightsForAeroponics[Indoor Plant Lights for Aeroponics https://aeroponicsdiy.com/indoor-plant-lights-for-aeroponics/]
****


=== 1.3.1: Light/Dark Period
****
The amount of light exposure should be limited as per the plants light/dark period (a.k.a., critical day length or photoperiod); 14 to 18 hours of light for long-day (short-night) plants, 8 to 12 hours of light (with a continuous dark period of 14 to 16 hours) for short-day (long-night) plants.footnote:6-WhatIsTheRightLightIntensityAndIlluminationLength[What is the right light intensity and illumination length? https://hortione.com/2020/12/the-right-light-intensity-which-distance/]footnote:8-LightIntensityAndPhotoperiodInfluenceTheGrowthAndDevelopmentOfHydroponicallyGrownLeafLettuce[Kang, J.H., KrishnaKumar, S., Atulba, S.L.S. et al. Light intensity and photoperiod influence the growth and development of hydroponically grown leaf lettuce in a closed-type plant factory system. Hortic. Environ. Biotechnol. 54, 501–509 (2013). https://doi.org/10.1007/s13580-013-0109-8]footnote:9-ComparativeGrowthPhotosyntheticPigmentsAndOsmolytesAnalysisofHempSeedlingsUnderAnAeroponicsSystemwithDifferentLEDLightSources[Islam, Jahirul et al. “Comparative Growth, Photosynthetic Pigments, and Osmolytes Analysis of Hemp (Cannabis Sativa L.) Seedlings under an Aeroponics System with Different LED Light Sources.” Horticulturae 7.8 239. Web. https://doi.org/10.3390/horticulturae7080239]
****


=== 1.3.2: Usable Light Spectrum
****
Infra-red light should be filtered out, as to utilize only the portion of the light spectrum needed for plant growth and to reduce heat build up inside of the plant cells; blue light (mid-400 nm) is beneficial for seedling and vegetative growth; red light (600 to 640 nm) is beneficial for germination and generative (flowering/blooming) growth.footnote:5-IndoorPlantLightsForAeroponics[Indoor Plant Lights for Aeroponics https://aeroponicsdiy.com/indoor-plant-lights-for-aeroponics/]footnote:7-UnderstandingLightEnergyForPlantGrowth[Understanding Light Energy for Plant Growth: Aeroponic growing systems For greenhouses and indoors the natural solution for CLEAN Aeroponic food indoors. https://www.aeroponics.com/aero65.htm]
****


=== 1.3.3: Light Intensity
****
The required light intensity, or photosynthetic photon flux density (PPFD), varies per plant and growth phase; e.g., the PPFD for tomato/cucumber is 75 to 300 umol/m2/s for seedling phase, 250 to 400 umol/m2/s for vegetative phase, & 600+ umol/m2/s for generative phase.footnote:6-WhatIsTheRightLightIntensityAndIlluminationLength[What is the right light intensity and illumination length? https://hortione.com/2020/12/the-right-light-intensity-which-distance/]footnote:8-LightIntensityAndPhotoperiodInfluenceTheGrowthAndDevelopmentOfHydroponicallyGrownLeafLettuce[Kang, J.H., KrishnaKumar, S., Atulba, S.L.S. et al. Light intensity and photoperiod influence the growth and development of hydroponically grown leaf lettuce in a closed-type plant factory system. Hortic. Environ. Biotechnol. 54, 501–509 (2013). https://doi.org/10.1007/s13580-013-0109-8]footnote:9-ComparativeGrowthPhotosyntheticPigmentsAndOsmolytesAnalysisofHempSeedlingsUnderAnAeroponicsSystemwithDifferentLEDLightSources[Islam, Jahirul et al. “Comparative Growth, Photosynthetic Pigments, and Osmolytes Analysis of Hemp (Cannabis Sativa L.) Seedlings under an Aeroponics System with Different LED Light Sources.” Horticulturae 7.8 239. Web. https://doi.org/10.3390/horticulturae7080239]
****


=== 1.4: CO2 Concentration
****
Elevated carbon dioxide (CO2) concentration yields increased photosynthesis; e.g., in one study, white clover grown under elevated CO2 of 600 ppm, for 8 years, retained a 37% increase in photosynthesis.footnote:10-EffectsOfElevatedCarbonDioxideOnPhotosynthesisAndCarbonPartitioning[Thompson, Michael et al. “Effects of Elevated Carbon Dioxide on Photosynthesis and Carbon Partitioning: A Perspective on Root Sugar Sensing and Hormonal Crosstalk.” Frontiers in physiology vol. 8 578. 8 Aug. 2017. https://dx.doi.org/10.3389%2Ffphys.2017.00578]
****



== User Stories

The Airponics Chamber's stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.



== Data Structures
This section covers each data structure type in the *Airponics Chamber*.


