title: 'Imran Ali Lakhiar, Jianmin Gao, Tabinda Naz Syed, Farman Ali Chandio & Noman Ali Buttar (2018). "Modern plant cultivation technologies in agriculture under controlled environment: a review on aeroponics", Journal of Plant Interactions, 13:1, 338-352.'
url: 'https://doi.org/10.1080/17429145.2018.1472308'
