id: 1.1
name: "Environment Temperature"
statement: "In an aeroponics system, the ideal environment temperature for plant growth is 25 to 30 degrees celsius"
derivedFrom:
- "0-References/2-DesignAndImplementationOfIoTSystemForAeroponicChamberTemperatureMonitoring.yaml"
