id: 1.1
name: "Environment Temperature"
statement: "In an aeroponics system, The optimum temperature range for successful plant growth is 15 to 30 °C."
derivedFrom:
- "0-References/2-DesignAndImplementationOfIoTSystemForAeroponicChamberTemperatureMonitoring.yaml"
- "0-References/12-ModernPlantCultivationTechnologiesInAgricultureUnderControlledEnvironment.yaml"
