id: 1.1.1
name: "Environment Temperature"
statement: "In an aeroponics system, the nominal environment temperature range should be between 4 and 30 degrees celsius, with an optimal temperature range between 15 and 20 degrees celsius."
derivedFrom:
- "0-References/2-ManualOnQualitySeedPotatoProductionUsingAeroponics.yaml"
